CREATE TABLE "gds_submissions" (
	"id" serial PRIMARY KEY NOT NULL,
	"application_id" varchar(255) NOT NULL,
	"evaluation_id" varchar(255) NOT NULL,
	"external_user_id" varchar(255) NOT NULL,
	"satisfied" integer NOT NULL,
	"no_activities" integer NOT NULL,
	"empty" integer NOT NULL,
	"upset" integer NOT NULL,
	"good" integer NOT NULL,
	"bad" integer NOT NULL,
	"happy" integer NOT NULL,
	"helpless" integer NOT NULL,
	"stay_at_home" integer NOT NULL,
	"problems_of_memory" integer NOT NULL,
	"wonderful_to_stay_alive" integer NOT NULL,
	"useless" integer NOT NULL,
	"full_of_energy" integer NOT NULL,
	"hopeless" integer NOT NULL,
	"unlucky" integer NOT NULL,
	"total_score" integer NOT NULL,
	"classification" varchar(50) NOT NULL,
	"submitted_at" timestamp DEFAULT now()
);
